# Uncomment this line to define a global platform for your project

platform :ios, '7.1'
use_frameworks!

target "MyTweet" do

pod 'MBProgressHUD', '~> 0.8'
pod 'SVProgressHUD'
pod 'PureLayout'
pod 'AFNetworking', '~> 2.0'
pod 'SDWebImage','~> 3.7'
pod 'PrettyTimestamp'
#pod 'FontAwesome-iOS'

end